apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          # Uruchamiamy Redis z naszą konfiguracją
          command:
            - "redis-server"
            - "/usr/local/etc/redis/redis.conf"
          ports:
            - containerPort: 6379
          volumeMounts:
            # Montujemy plik redis.conf z ConfigMap
            - name: redis-config-volume
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
            # Montujemy PVC w /data, bo w redis.conf jest dir /data
            - name: redis-data-volume
              mountPath: /data
      volumes:
        - name: redis-config-volume
          configMap:
            name: redis-config
            items:
              - key: "redis.conf"
                path: "redis.conf"
        - name: redis-data-volume
          persistentVolumeClaim:
            claimName: redis-pvc
---
# Opcjonalnie: Service do dostępu z zewnątrz/innych Podów:
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
