# k8s/interface-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-interface
  labels:
    app: scraper-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-interface
  template:
    metadata:
      labels:
        app: scraper-interface
    spec:
      containers:
        - name: scraper-interface
          image: projekt-interfejs:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: interface-service
spec:
  selector:
    app: scraper-interface
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000   # dzięki temu App jest dostępna na localhost:30000
  type: NodePort
