apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379

    save 60 1
    appendonly yes
    appendfsync everysec

    dir /data
